### PR TITLE
O'Doom Fx

### PR DESCRIPTION
**Pull request by exabrial**
O'Doom is a small hardware company. We are making guitar effects pedals, midi controllers, and guitar amps. Our hardware designs and software will be open source so users can repair them or build them from scratch for personal use.

### CODE REVIEW

**Comment by Arachnid** [comment]
I'm sorry, but pids in the 0x0*** range are reserved. Please choose another.

**Comment by Arachnid** [comment]
Also, please link to your hardware designs under a suitable OSHW license.

**Comment by peternewman** [comment]
A minor point @Arachnid . It doesn't mention the reserved nature of 0x0*** on the website.

**Comment by Arachnid** [comment]
It does, right here: http://pid.codes/1209/

**Comment by peternewman** [comment]
Oops, so it does. It's not on the How To Get a PID page though http://pid.codes/howto/

**Comment by Arachnid** [comment]
No, but there it says:

> You may request any number that is not in use, except those reserved as described on the VID page.

**Pull request closed without merging**
