### PR TITLE
A pid for the Omzlo USB controller

### PR DESCRIPTION
**Pull request by omzlo**

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for your submission!

In order to grant you a PID, your hardware and software both need to be licensed under a recognised open-source license. While you've got a hardware repository, it contains only a PDF. Can you check in your source files for the hardware, please?

**Comment by omzlo** [comment]
Hi,
The source files have just been uploaded in https://github.com/omzlo/omzlo-usb-interface-hardware/tree/master/v10
Many thanks for this nice initiative!

**Comment by peternewman** [comment]
@Arachnid is the "Require branches to be up to date before merging" in Settings>Branches>Protected branches>Master bit turned on to protect against this, or at least to flag it up?

**Comment by Arachnid** [comment]
@peternewman It is now!

**Pull request merged**
