### PR TITLE
PIDs for Blinky Pendant

### PR DESCRIPTION
**Pull request by cibomahto**
Hello, we're releasing a new project called BlinkyPendant, and I'd like to request two PIDs for it- one for the bootloader (DFU compatible), and the other for the application. The BlinkyPendant is a low-cost POV wand that can be reprogrammed to show different patterns. It's about 10cm long, runs on two coincell batteries, and is designed to be low cost.

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for your pull request!

Please read carefully the guidelines at http://pid.codes/howto. Specifically, PIDs in the range 0x1000 - 0x1FFF are reserved for the original owner of the PID. Please select unused PIDs outside this range.

If you can notate the Apache License as 'APL', too, that'd be appreciated.

**Comment by cibomahto** [comment]
Ah, sorry about that! Hopefully fixed oth issues now.

**Comment by Arachnid** [comment]
Thanks. One final issue: The site prefixes the orgname to each product name, so currently your PIDs would show up as "Blinkinlabs Blinkinlabs LED Pendant". If you remove 'Blinkinlabs' from each product name, it'll show up correctly.

**Comment by cibomahto** [comment]
Thank you!!

**Pull request merged**
