### PR TITLE
PID Request for JRC Polymer Keyboard

### PR DESCRIPTION
**Pull request by jrobsonchase**
Hi! I'd like to request PID 9200 for my keyboard project.

Thanks!

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for your application! In order to grant you a PID, both your firmware and hardware design source files need to be provided, licensed under open-source licenses. Please feel free to open a new PR once that's the case.

**Comment by jrobsonchase** [comment]
I thought I had done so - the firmware, case, and pcb designs are all linked from the site listed in the project info (https://gitlab.com/polymer-kb/polymer). Is there a different way I was supposed to provide them?

**Comment by jrobsonchase** [comment]
@Arachnid For example, the [keyboardio](https://github.com/pidcodes/pidcodes.github.com/blob/51c99d98d2a714de8a9edf5efe50e870222fabac/1209/2300/index.md) [files](https://github.com/obra/pidcodes.github.com/blob/master/1209/2301/index.md) are organized in much the same way as my request with an overview site and a link to the firmware repository (though I didn't see any hardware source aside from "it comes with the board" on the main site). Can you be more specific as to what you're looking for?

**Comment by Arachnid** [comment]
Apologies, I missed them on my first look through.

**Pull request merged**
