### PR TITLE
pid request for volume knob project

### PR DESCRIPTION
**Pull request by 0xa10**
Requesting pid a107 for my volume knob project, which runs on an rpi Pico or any other board based on the RP2040

### CODE REVIEW

**Comment by 0xa10** [comment]
Hi, any way to progress this? Thanks

**Review by tannewt — APPROVED** [review]
Looks ok. Unlicense code that runs on third-party board (raspberry pi pico).

**Comment by tannewt** [comment]
Please uppercase the PID to match the others and fix the CI.

**Comment by 0xa10** [comment]
Thanks. Fixed casing now

**Comment by 0xa10** [comment]
Hi, would appreciate another look at this and merging if OK now
thanks

**Comment by 0xa10** [comment]
thank you!

**Pull request merged**
