### PR TITLE
Fixed index.md file(s)

### PR DESCRIPTION
**Pull request by SandeepanSengupta**
All sources are pointing to [newer profile](http://github.com/SandeepanSG) i.e. @SandeepanSG instead of @SandeepanSengupta

### CODE REVIEW

**Comment by Arachnid** [comment]
Can you please resolve the conflicts with head?

**Comment by SandeepanSengupta** [comment]
@Arachnid 
What do I have to do to resolve this conflict ?

I've already moved the fork from this older profile to newer one [here](https://github.com/sandeepansg/pid.codes)

Would you please guide me through ?

**Comment by sandeepansg** [comment]
Migrating to #501

**Comment by Arachnid** [comment]
Your PR has conflicting files with head. You'll need to resolve those (or create a new PR without the conflicts) before it can be merged.

**Comment by sandeepansg** [comment]
Please close this pull request

**Pull request closed without merging**
