### PR TITLE
sinara/stabilizer: add org and pid

### PR DESCRIPTION
**Pull request by jordens**
* org/Sinara: add Sinara organization
* 1209/392F: add Stabilizer PID

Signed-off-by: Robert Jördens <rj@quartiq.de>

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Please add a license file at the source location to clear document it's license.

**Comment by jordens** [comment]
Added in 
https://github.com/sinara-hw/Stabilizer/commit/0b9de4e4141a93fe486f3e6b2662b2a4624debf5 (hardware design)
Already existing for software (https://github.com/quartiq/stabilizer/blob/master/LICENSE)

**Review by tannewt — APPROVED** [review]
Thank you!

**Review by tannewt — COMMENTED** [review]
Unfortunately, the CI hasn't run on this. Can you force push again? I think that will trigger it.

**Comment by jordens** [comment]
rebased

**Comment by tannewt** [comment]
Thanks!

**Pull request merged**
