### PR TITLE
Add codes for KnightOS

### PR DESCRIPTION
**Pull request by SirCmpwn**
KnightOS acts as a generic hub and userspace applications can plug
themselves into it. We're reserving a code for the hub itself, as well
as for our MTP userspace service.

### CODE REVIEW

**Comment by Arachnid** [comment]
Are you sure you wouldn't prefer `ADD5` or `CA1C`? ;)

**Comment by SirCmpwn** [comment]
Those are excellent choices. We should totally use `CA1C`. Update incoming.

**Comment by SirCmpwn** [comment]
Whoops! Can you fix that @Arachnid?

**Comment by Arachnid** [comment]
They're displayed as {orgname} {devicename}. If you don't want the repetition, you can submit a PR that removes "KnightOS" from the device name.

**Pull request merged**
