### PR TITLE
Add org bonzi, and PID 6939

### PR DESCRIPTION
**Pull request by bonzi**

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
The keebs.bonzi.sh links don't work. Where is the hardware source?

**Comment by bonzi** [comment]
Sorry about that, Repo's are now updated to reflect the correct project, and the website has been enabled (Sorry about its brevity, the project is still in development)

**Comment by tannewt** [comment]
What software does it run?

I'd suggest a non-GPL license for hardware since hardware is different than software. (I won't block this merge though if you want to stick with GPL.) More info here: https://www.oshwa.org/faq/#what-license-to-use and here: http://www.ladyada.net/library/openhardware/license.html

**Comment by bonzi** [comment]
> What software does it run?
https://github.com/qmk/qmk_firmware/

> I'd suggest a non-GPL license for hardware since hardware is different than software. (I won't block this merge though if you want to stick with GPL.) More info here: https://www.oshwa.org/faq/#what-license-to-use and here: http://www.ladyada.net/library/openhardware/license.html

I chose to use the GPL soley out of the fact that QMK uses it, However I am very much happy to switch to an OSHWA certified licence (After all, the KiCad project files and etc will be on GitHub).

**Comment by bonzi** [comment]
CC BY-SA 4.0 licence has been implemented. Everything should be kosher now.

**Review by tannewt — APPROVED** [review]

**Pull request merged**
