### PR TITLE
PID request for SAMboyantion

### PR DESCRIPTION
**Pull request by SandeepanSengupta**
Implementation of UF2 by Microsoft
Although it uses [this](https://github.com/awatterott/uf2-samd21) UF2 port, a  custom VID/PID pair is required

### CODE REVIEW

**Comment by SandeepanSengupta** [comment]
Forgot to add License file, closing this one to add License

**Comment by SandeepanSengupta** [comment]
Mistakenly closed.
Requesting Re-Open

**Comment by Arachnid** [comment]
Why does this PR modify someone else's existing PID allocation?

**Comment by SandeepanSengupta** [comment]
@Arachnid, I used to own both intelectron.in and iobitz.com domain and the associated devices.
Both of these orgs are dissolved now (and assets merged), so as the original owner I requested three things.
1) Disassociate PID allocations for intelectron.in/Intelectron India and free up the PIDs (**_A8B0_** and **_A8B1_**) for everyone
2) Migrate PIDs allocated for IObitZ (**b010** and **b101**) to me (##Sandeepan)
3) In this thread I request new sets of PIDs for another device/bootloader

**Comment by SandeepanSengupta** [comment]
@Arachnid, I used to own both intelectron.in and iobitz.com domain and the associated devices.
Both of these orgs are dissolved now (and assets merged), so as the original owner I requested three things.
1) Disassociate PID allocations for intelectron.in/Intelectron India and free up the PIDs (**_A8B0_** and **_A8B1_**) for everyone
2) Migrate PIDs allocated for IObitZ (**_b010_** and **_b101_**) to me (**Sandeepan**)
3) In this thread I request new sets of PIDs (**_E0E0_**, **_E0F0_**, **_EEEE_** and **_EEEF_**) for another device/bootloader (a CDC-MSC composite bootloader that requires two sets of ID for each emulation, one in bootloader ode, one when running firmware code)

Hope this will clear some confusions

**Comment by SandeepanSengupta** [comment]
@Arachnid , I used to own both intelectron.in and iobitz.com domain and the associated devices.
Both of these orgs are dissolved now (and assets merged), so as the original owner I requested **_FOUR_** things.
1) Disassociate PID allocations for intelectron.in/Intelectron India and free up the PIDs (**_A8B0_** and **_A8B1_**) for everyone
2) Migrate PIDs allocated for IObitZ (**_b010_** and **_b101_**) to me (**Sandeepan**)

In this thread I am...
3) Updating index file and pointing the hyperlink to my new URL/website instead of my github page
4) Requesting new sets of PIDs (**_E0E0_**, **_E0F0_**, **_EEEE_** and **_EEEF_**) for another device/bootloader (a CDC-MSC composite bootloader that requires two sets of ID for each emulation, one in bootloader ode, one when running firmware code)

Hope this will clear some confusions

**Comment by Arachnid** [comment]
Okay; can you please open a separate PR for each operation?

**Pull request closed without merging**
