### PR TITLE
Request for PID 2552 for WeIO

### PR DESCRIPTION
**Pull request by ks156**

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for your pull request! If the hardware is something you've designed, that also needs to be licensed under an open-source license, and you need to link to it in your PID.

**Comment by ks156** [comment]
The hardware is indeed open-source, and can be found here : https://github.com/nodesign/weioBoard

How do you want I link it to the PID ? With a comment after this line https://github.com/pidcodes/pidcodes.github.com/pull/213/files#diff-e2ef97a56e3408a75e780c9f01c50063R8 ?

**Comment by Arachnid** [comment]
Yes, the body after that line is Markdown, so you can include a markdown-syntax link to the hardware repository.

**Comment by ks156** [comment]
@Arachnid thank you for the precision. I've added a line to point the hardware files

**Comment by ks156** [comment]
Thank you 😃

**Comment by ks156** [comment]
@Arachnid I asked a PID for WeIO, but I want to be a little more ambitious.

I'm currently writing a firmware based on [RIOT-OS](https://github.com/RIOT-OS/RIOT) that implements the [electrolink protocol](https://github.com/projectiota/electrolink/blob/master/electrolink-protocol.md).

Even if I'm developing it for the WeIO board now, I want support more boards in the future. With RIOT, I'll have a generic implementation for boards that are supported by RIOT.

Electrolink is part of [ProjectIota](http://projectiota.github.io/), that aims to provide standardized tools for IoT devices.

Can I update the file ```1209/2552/index.md``` with the new informations (basically WeIO -> electrolink) and change ```org/weio/``` to ```org/ProjectIota/```

I'm sorry to come with this request few days after my initial pull request. I should have think better earlier 😄

**Comment by Arachnid** [comment]
Yes, by all means submit an updated PR.

**Comment by ks156** [comment]
@Arachnid : Thank you 😄  
Here's the new pull request : https://github.com/pidcodes/pidcodes.github.com/pull/219

**Pull request merged**
