### PR TITLE
Switch the markdown engine to kramdown as GitHub are getting rid of redcarpet :(

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
This bumps the starting list of broken links up to 15, as the ones in the body of pages are now turned into hyperlinks too.

**Comment by peternewman** [comment]
This wants to go in before #200 so I can ignore or fix them there too.

**Comment by Arachnid** [comment]
Uhoh. I'm not sure this is going to work long-term. Github keeps sending me this:

> The page build completed successfully, but returned the following warning:

> You are currently using the 'redcarpet' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

**Comment by peternewman** [comment]
Interesting, I've not had those on my branch @Arachnid , just messages that the pid.codes domain is already used.

I'll try and update this to use kramdown then.

**Comment by Arachnid** [comment]
Thanks! Will the missing extensions break anything?

**Comment by peternewman** [comment]
Yes, it puts me back to square one with the autolinking:
https://github.com/gettalong/kramdown/issues/306

Which is rather frustrating, as they work fine in the markdown direct on GitHub, e.g.:
https://github.com/peternewman/pidcodes.github.com/blob/master/org/misfittech/index.md
Compare to:
https://peternewman.github.io/pidcodes.github.com/org/misfittech/

Given it doesn't do what it says on the tin, I'm not sure how many other features don't match the direct markdown rendering within GitHub. :(

**Comment by Arachnid** [comment]
Bugger. Thanks again for your hard work on this, though.

**Comment by peternewman** [comment]
I guess this probably wants merging if it keeps GitHub happy, even if it is a step backwards in my opinion.

**Pull request merged**
