### PR TITLE
PID request DI-Lambda-AVR, new org: Koi Science

### PR DESCRIPTION
**Pull request by xl0**

### CODE REVIEW

**Comment by xl0** [comment]
Hello.

All good? Is any action required from my side?

**Comment by Arachnid** [comment]
Can you please link to the source code, also published under an open-source license?

**Comment by xl0** [comment]
Schematics/layout: https://github.com/koi-science/DI-Lambda-schematics-avr
Firmware source code (very unimpressive ATM, will be using HID soon): https://github.com/koi-science/DI-Lambda-firmware-Arduino
Desktop app: https://github.com/koi-science/DI-Lambda-qlambda

**Comment by xl0** [comment]
Do you support multiple source: entries?

**Comment by Arachnid** [comment]
No, but you can add text in markdown format to the body of the entry with additional information.

**Comment by xl0** [comment]
Pushed.  Please check.

**Pull request merged**
