### PR TITLE
Adding new Org [MetalBoards] and Pid [8191]

### PR DESCRIPTION
**Pull request by billyjbryant**
### Description

MetalBoards is creating a new 4 x 4 Macro KeyPad which is called InsaneMacroPad. 

The desired PID is 1209/8191

owner: MetalBoards
license: MIT
site: https://github.com/MetalBoards/InsaneMacroPad/README.md
source: https://github.com/MetalBoards/InsaneMacroPad

### CODE REVIEW

**Review by GeekTechPC — APPROVED** [review]
I find this interesting and would love to see where they take this

**Comment by billyjbryant** [comment]
@tannewt are you able to approve the pre-req workflows for us?

**Review by GeekTechPC — APPROVED** [review]
I can see you're working with an open source code and I hope to see this being a further course

**Review by tannewt — CHANGES_REQUESTED** [review]
https://github.com/MetalBoards/InsaneMacroPad/README.md link doesn't work. Please fix. Repo license and files look ok.

**Comment by billyjbryant** [comment]
> https://github.com/MetalBoards/InsaneMacroPad/README.md link doesn't work. Please fix. Repo license and files look ok.

Sorry about that, I fixed it. We currently do not have a website, this is a WiP. As soon as we have an official site I will submit another PR to update that information accordingly.

**Review by tannewt — APPROVED** [review]

**Comment by billyjbryant** [comment]
Who can merge this PR?

**Comment by billyjbryant** [comment]
@tannewt is there anyone else that has the ability to merge, I'm sure you are busy, so don't want to keep bugging you :)

**Comment by tannewt** [comment]
@Arachnid Is the original person but got burned out. I'm the only person now.

**Pull request merged**
