### PR TITLE
PID request: F00C for github::samveen/pico-mpy-2fa-totp

### PR DESCRIPTION
**Pull request by samveen**
PID request: F00C for github::samveen/pico-mpy-2fa-totp

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
The license you use is weird and I don't consider it open source.

**Comment by samveen** [comment]
@tannewt As mentioned in the [LICENSE](https://github.com/samveen/pico-mpy-2fa-totp/blob/main/LICENSE) file, it's a modified 2-clause BSD, adding 2 self-nullifying but humourous clauses to the [original](https://opensource.org/license/bsd-2-clause). A simple comparison should clear up any doubts.

**Comment by tannewt** [comment]
> @tannewt As mentioned in the [LICENSE](https://github.com/samveen/pico-mpy-2fa-totp/blob/main/LICENSE) file, it's a modified 2-clause BSD, adding 2 self-nullifying but humourous clauses to the [original](https://opensource.org/license/bsd-2-clause), as seen on opensource.org. A simple comparison should clear up any doubts.
> 
> I've modified the formatting back to the original source so that it's easier to review and compare.

Please do the title of the LICENSE as well. That way GitHub can identify it. Licenses aren't a great place for humor.

**Comment by samveen** [comment]
> Please do the title of the LICENSE as well. That way GitHub can identify it. Licenses aren't a great place for humor.

Done. Please review.

**Comment by tannewt** [comment]
Sorry, I thought you had removed clauses 3 and 4. I don't consider a *modified* BSD license open source for this repo.

**Comment by samveen** [comment]
Thank you for your time and effort.

**Pull request closed without merging**
