### PR TITLE
Smart House

### PR DESCRIPTION
**Pull request by LifeToDevice**

### CODE REVIEW

**Comment by LifeToDevice** [comment]
Hello! What's wrong?

**Comment by LifeToDevice** [comment]
I fix it

**Comment by Arachnid** [comment]
Thanks for your pull request.

We only grant PIDs for products that are ready for production or release; I see you've checked in a schematic, but not a PCB layout. If you haven't yet designed a layout or manufactured PCBs, you're welcome to use the [test PID](http://pid.codes/1209/0001/) in the mean time.

Please also include a short description in your PID file of what the device is and what it does.

**Comment by LifeToDevice** [comment]
Hello! I add PCB and description to PID file

**Comment by LifeToDevice** [comment]
Hello! I added device description to PID file and PCB files to repository. You will consider my request?

**Comment by LifeToDevice** [comment]
Thank you very much!

**Pull request merged**
