### PR TITLE
Added Robotips organisation page and pid A602 for RTBoard

### PR DESCRIPTION
**Pull request by sebcaux**

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for your pull request! Can you clarify what this is? Is there a hardware component?

Also, can you please clean up the window-style line endings?

**Comment by sebcaux** [comment]
Thank you for your fast answer, I removed windows-style line endings and I added a description for RTBoard. Does it need more information ?

**Comment by Arachnid** [comment]
Is there a hardware component to this, or is it firmware intended to run on widely available development boards?

**Comment by sebcaux** [comment]
This PID is only for one board, RTBoard the name of our board with USB comunication. But RTProg repo is used for other boards, without USB.

**Comment by Arachnid** [comment]
In that case, your hardware design files need to be published somewhere under an OSHW license, and you need to link to them from your PID entry.

**Comment by sebcaux** [comment]
I publish it on https://hackaday.io/project/20901-rtboard-10

**Comment by Arachnid** [comment]
Is there firmware as well? How is that licensed?

**Comment by sebcaux** [comment]
The firmware is included in RTProg repository : https://github.com/Robotips/rtprog

**Pull request merged**
