### PR TITLE
Dinoctopus theremin

### PR DESCRIPTION
**Pull request by bjonnh**
Adding my two MIT licensed projects.

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
These look like software projects. What hardware do they run on?

**Comment by bjonnh** [comment]
These are PlatformIO projects. For Raspberry Pico (shouldn't be too hard to adapt to others).

I'm also making specific boards for those but the designs aren't working yet.

**Comment by bjonnh** [comment]
License for the hardware will be MIT as well.

**Comment by bjonnh** [comment]
I just added the Kicad files for the first project:
https://github.com/bjonnh/dinoctopus/tree/main/hardware/electronics

Still working on enclosure and the prototype of the second one.

**Review by tannewt — APPROVED** [review]

**Pull request merged**
