### PR TITLE
PID request for ES3ink board

### PR DESCRIPTION
**Pull request by dronecz**

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Repo link doesn't work. Please also include a link in the hardware repo's readme to the software that will use this PID. (Your CircuitPython branch.)

**Comment by dronecz** [comment]
Sorry, I created repo for my board and link now works. Are information in it OK to move this forward? Thanks

**Review by tannewt — CHANGES_REQUESTED** [review]
No, you actually need the source published to be considered open source. You may want a PID from ESP instead. They don't require open source.

**Comment by dronecz** [comment]
@tannewt Ok, so if I upload source files for the board to the Github, that will be enough to finish this PR?

**Comment by dhalbert** [comment]
@tannewt Could you re-review? Thanks.

**Review by tannewt — APPROVED** [review]

**Pull request merged**
