### PR TITLE
Request PID for FreeSRP software-defined radio

### PR DESCRIPTION
**Pull request by lukaslaobeyer**
This pull request is to request a PID for the FreeSRP software-defined radio.

The main project website is: http://freesrp.org
And all the source code can be found at: http://github.com/FreeSRP
PDF schematics and USB controller firmware are located here: http://github.com/FreeSRP/usb-firmware

Thank you!

### CODE REVIEW

**Comment by Arachnid** [comment]
Are the hardware designs available under an open-source license? If so, can you please add a link to the repository on the PID page?

**Comment by lukaslaobeyer** [comment]
Yes, the hardware designs are available under Creative Commons Attribution-ShareAlike. I'm using CircuitMaker for this project, so the actual "source" is hosted [here](https://circuitmaker.com/projects/details/lukas-lao-beyer/freesrp). I've created [this repo](https://github.com/myriadrf/freesrp) to host links to the relevant sources -- is that a good link to use for the PID site?

**Comment by Arachnid** [comment]
Okay... but now you don't have a link to the software?

**Comment by lukaslaobeyer** [comment]
The README in that repository has a links to the software and firmware sources (as they all are in separate repos). If it's possible to add more than one link to the PID file, I can do that, as well. Thank you!

**Pull request merged**
