### PR TITLE
Request PID 1209:F502 for Silicognition RP2040-Shim

### PR DESCRIPTION
**Pull request by xorbit**
https://github.com/xorbit/RP2040-Shim

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
What software will this run? Please link to a corresponding repo from the hardware repo README.

**Comment by xorbit** [comment]
It's already in there:
"The hardware is sold with [CircuitPython](https://github.com/adafruit/circuitpython) pre-installed."

But I can't get my PR to support this board pushed to CircuitPython until I have a PID.  Chicken and egg.

**Comment by xorbit** [comment]
This is quite sad @tannewt.  Blocked for no reason other than that you didn't look.  Now it's just sitting in limbo.

**Comment by tannewt** [comment]
> It's already in there: "The hardware is sold with [CircuitPython](https://github.com/adafruit/circuitpython) pre-installed."
> 
> But I can't get my PR to support this board pushed to CircuitPython until I have a PID. Chicken and egg.

You should link to your own copy of CircuitPython with the changes for your board from the hardware README to satisfy the PID.codes requirements. It doesn't need to be upstream to get a PID.

> This is quite sad @tannewt. Blocked for no reason other than that you didn't look. Now it's just sitting in limbo.

I *volunteer* to administer this *free* USB PID source and go through all open PRs when I do, starting with the oldest. If you need one quickly, then buy a USB VID or a PID one from someone. See "My project isn’t OSH-licensed, can I still get a PID?" on [the FAQ](https://pid.codes/faq/) for places to purchase one.

**Comment by xorbit** [comment]
My excuses, I thought that this was another project sponsored by Adafruit, I didn't know this was maintained on your own time.

Is this policy to point to my own code fork new?  Because I'm pretty sure I did the exact same thing I did here (point to upstream CircuitPython before the code was there) when I requested the PID for my M4-Shim.  Then once I had the PID I pushed the code that used it and opened a CircuitPython PR.  It doesn't seem this new policy would add any guarantees the code will stay open since someone can just delete their fork after they get the PID.

I updated the link to point to my repo fork for the time being.
After I get my CircuitPython code merged I intend to change the link back to upstream CircuitPython since I may delete my fork.

**Comment by tannewt** [comment]
> My excuses, I thought that this was another project sponsored by Adafruit, I didn't know this was maintained on your own time.

Nope, I offered to help with it since it's commonly used for CircuitPython. It isn't an Adafruit thing.

> Is this policy to point to my own code fork new? Because I'm pretty sure I did the exact same thing I did here (point to upstream CircuitPython before the code was there) when I requested the PID for my M4-Shim. Then once I had the PID I pushed the code that used it and opened a CircuitPython PR. It doesn't seem this new policy would add any guarantees the code will stay open since someone can just delete their fork after they get the PID.

I don't think so. My goal is to ensure that the code was available at one point. Any of this info could be removed after the fact. If we find that happens, I'd assume we'd not approve any more PIDs for the person.

> I updated the link to point to my repo fork for the time being. After I get my CircuitPython code merged I intend to change the link back to upstream CircuitPython since I may delete my fork.

Thank you!

**Review by tannewt — APPROVED** [review]

**Pull request merged**
