### PR TITLE
Add HydraBus org and HydraUSB3 & HydraUSB3 bootloader PIDs

### PR DESCRIPTION
**Pull request by bvernoux**
Requesting the allocation of 1209:B569 (HydraUSB3 bootloader)
Requesting the allocation of 1209:C569 (HydraUSB3)

HydraUSB3 Open Source firmware & lib [Apache License 2.0](https://github.com/hydrausb3/hydrausb3_fw/blob/main/LICENSE)
https://github.com/hydrausb3/hydrausb3_fw

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Please link to the open hardware source files here and from the firmware readme too. We do not provide USB PIDs for official code on closed source hardware.

**Comment by bvernoux** [comment]
> Please link to the open hardware source files here and from the firmware readme too. We do not provide USB PIDs for official code on closed source hardware.

Thanks for your answer
Actual status is all source code firmware/bsp, host(to be delivered soon with USB firmware bsp & example) are fully open source under [Apache License 2.0](https://github.com/hydrausb3/hydrausb3_fw/blob/main/LICENSE) it was already lot of work during lot of month on my spare time provided for free to everyone (based on blob and chinese comment...).

The hardware HydraUSB3 v1 is produced with High Quality PCB/Components is not open source today.
My aim on that project is not to gain money but to provide the best possible board at the best possible price (with a small margin mainly to cover production cost/website/digi-key fees...).
I plan to release it with an Open Source License (all is done with fully open source tools like KiCad v6) but not until I sell enough board (at least 400 boards) to cover my production costs.

I hope those explanations/clarification will help to provide free USB VID/PID like that I will release fully open source USB driver and example (fully reversed and rewritten based on WCH CH569 closed lib/blob) which is clearly the first open source project with an MCU (RISC-V) to bring such amazing high speed peripherals/bsp accessible to everyone (even those who build their own board based on WCH CH569)

**Comment by tannewt** [comment]
Thank you for the explanation. Unfortunately, we don't provide PIDs until projects are open sourced. Until then, feel free to use a test PID.

**Comment by hansfbaier** [comment]
@tannewt The HOWTO in https://pid.codes/howto/ actually only seems to lay out the following conditions:
```
If your project does not meet the following criteria, your pull request will be rejected:

    Publicly available source code repository…
    Containing schematics or source code for a device with a USB interface…
    Licensed under a recognized open source or open source hardware license. Your source code repository must contain a LICENSE file attesting to this fact.
```
Especially, the firmware which is open source is not tied to the mentioned hardware, but can also easily be run and used on
other CH569 boards, for example my design, which is fully open hardware: https://github.com/hansfbaier/ch569-usb3-board/

**Comment by bvernoux** [comment]
For information HydraUSB3_USB open source Firmware/BSP and Host Tools(HydraUSB3_USB_benchmark) are now published on GitHub
 - The USB2 High Speed benchmark reach more than 48MBytes/s average
 - The USB3 Super Speed benchmark reach more than 330MBytes/s average

So far (as I have no other choice) the code use USB PID/VID from https://github.com/obdev/v-usb/blob/master/usbdrv/USB-IDs-for-free.txt PID 1500/0x05dc, VID 5824/0x16c0 for Vendor Class devices with libusb

See GitHub Links
- HydraUSB3_USB open source Firmware https://github.com/hydrausb3/hydrausb3_fw/tree/main/HydraUSB3_USB
- HydraUSB3_USB open source Generic WCH CH56x BSP (withUSB stack used by Firmware) https://github.com/hydrausb3/wch-ch56x-bsp
- HydraUSB3_USB_benchmark open source host tools https://github.com/hydrausb3/hydrausb3_host/tree/main/HydraUSB3_USB_benchmark

**Comment by bvernoux** [comment]
Could you provide an update on that PR ?

**Comment by tannewt** [comment]
I'm waiting for the hardware files of the Hydra3 to be open source before approving this PR. There are other ways to acquire a USB PID for closed source hardware.

**Comment by geissdoerfer** [comment]
@bvernoux I think you may have misread the conditions slightly. If you rephrase it and pull in the "not" from the introductory sentence, it reads: If your project does NOT contain schematics or does NOT contain source code for a device with a USB interface your pull request will be rejected. Your project does not contain schematics so one of the two conditions is true, which I guess is why your pull request is not getting merged.

**Comment by bvernoux** [comment]
> @bvernoux I think you may have misread the conditions slightly. If you rephrase it by pulling the "not" from the introductory sentence into the second bullet point, it reads: If your project does NOT contain schematics or does NOT contain source code for a device with a USB interface your pull request will be rejected.
> 
> Your project does not contain schematics so one of the two conditions is true, which I guess is why your pull request is not getting merged.

My product contains the schematic see https://github.com/hydrausb3/hydrausb3_hw/blob/main/HydraUSB3_V1R1_schematic.pdf
and contains the source code see https://github.com/hydrausb3/wch-ch56x-bsp & https://github.com/hydrausb3/hydrausb3_fw

So could you explain in what it is not compliant with the conditions ?

**Comment by geissdoerfer** [comment]
OK, I see. Then the problem is about the license. If you read the [how to](https://pid.codes/howto/), right under the three bullet points, it says: "If your project involves both hardware and software, both need to be licensed under recognised OSS and OSHW licenses." Looking at [your repo](https://github.com/hydrausb3/hydrausb3_hw) it seems that the schematics are not licensed under a recognised OSS and OSHW license. So, I guess, once you add a license to that repo, you should be eligible for a PID.

**Comment by tannewt** [comment]
PDF schematics are not considered open source. To be open source, it and the pcb file must be in the original editable form.

I volunteer to run this project. The previous maintainer burned out due to folks demanding they get a PID. There are other ways to get one. My goal for volunteering is to promote open source hardware and software. The Hydra3 isn't open source hardware.

**Pull request closed without merging**
