### PR TITLE
Add pid codes for the Keyboardio Model 100

### PR DESCRIPTION
**Pull request by obra**
Hi! We've got a new keyboard coming out and would love to reserve the two PID codes in this PR. Please let me know if you'd like anything in this fixed up.

Thanks!

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
Hi @obra, where are the hardware source files? I don't give folks the PIDs until hardware and software source is published. (The testing PIDs can be used until then.)

**Review by tannewt — CHANGES_REQUESTED** [review]
See above

**Comment by obra** [comment]
Is this a policy change? In the past (for both the Model 100 and the Atreus), open firmware was considered sufficient — open source release of hardware designs wasn’t a requirement.

**Comment by tannewt** [comment]
I don't think so. This says both: https://pid.codes/howto/

I do allow for firmware-only in the case that the applicant is making third party firmware. Otherwise, it is a carrot for folks to open source their hardware as well.

**Comment by obra** [comment]
My apologies. Having gone spelunking, at the time we got the PID for the Keyboardio Model 01, the prose was less clear, but still had the same intent.  Because we don't intend to publish hardware design files before the product ships, we can't reasonably request a pid.codes PID for the Model 100. It was probably getting on time to join USB-IF anyway ;)

**Pull request closed without merging**
