### PR TITLE
Make pid.codes an internal domain for htmlproofer

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
This needs some work still, or possibly a fix on the htmlproofer side.

**Comment by Arachnid** [comment]
Should this be committed, then?

**Comment by peternewman** [comment]
I think not until I've fixed the issues on the htmlproofer side thanks.

**Comment by peternewman** [comment]
See https://github.com/gjtorikian/html-proofer/pull/361

**Comment by peternewman** [comment]
This should be good to merge now @Arachnid .

**Pull request merged**
