### PR TITLE
Add Datanoise PicoADK.

### PR DESCRIPTION
**Pull request by DatanoiseTV**
Add Datanoise PicoADK - a Audio Development Kit for building Synthesizers and Music Hardware. Open Firmware.

### CODE REVIEW

**Comment by DatanoiseTV** [comment]
The PicoADK implements USB MIDI, MSC class and a custom vendor protocol for RPC.

**Review by tannewt — CHANGES_REQUESTED** [review]
I couldn't find hardware source files. Are they available?

We only grant PIDs to third parties for closed source hardware. First parties should open source both hardware and software. (Its meant to incentivize companies to do open source hardware and software.)

**Comment by DatanoiseTV** [comment]
Sorry, the hardware is not open source, but the firmware is.

**Comment by tannewt** [comment]
I'd recommend asking Raspberry Pi for a USB PID then: https://github.com/raspberrypi/usb-pid

**Pull request closed without merging**
