### PR TITLE
add rpga feather

### PR DESCRIPTION
**Pull request by skerr92**
adds RPGA Feather Circuitpython build PID. (will update with PR link to CircuitPython build)

### CODE REVIEW

**Comment by skerr92** [comment]
PR for CircuitPython https://github.com/adafruit/circuitpython/pull/9292

**Review by tannewt — CHANGES_REQUESTED** [review]
We don't grant PIDs before everything is open sourced. Until then, use a testing PID or acquire one from someone else.

**Comment by skerr92** [comment]
Hi Scott, the RPGA source repo is updated, I thought I pushed up the hardware files, etc... they are up now.

**Review by tannewt — APPROVED** [review]
:+1: MIT Kicad files.

**Pull request merged**
