### PR TITLE
Request for PID D017 for empiriKit controllers

### PR DESCRIPTION
**Pull request by larsgk**
In our spare time, we are creating enablers for affordable science controllers/sensors based on different off-the-shelf programmable hardware.

We are in the process of moving some things to WebUSB to ease deployment and use and need a proper VID/PID for the series of devices.

Code will be made available on the github account listed but most currently resides under https://github.com/larsgk

WebUSB and controller in action on example demo page: https://twitter.com/denladeside/status/817451203076427783

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for the PR! This sounds like a neat project.

Do you have a specific existing project you need a PID for? We can only issue you a PID if you have a specific device, with hardware and firmware both available under an open-source license.

**Comment by larsgk** [comment]
Hi @Arachnid ,

the project contains several parts that we are in the process of cleaning up and making available under BSD.

The current ("legacy") firmware is available here: https://github.com/larsgk/mbed_applications/tree/master/empirikit 
supporting some of the Freescale FRDM sensor/controller boards

It's currently getting fixed up for WebUSB and released on https://github.com/empirikit (and probably parts on mbed.org)

We are also doing the same with the WebAPP solution currently used here: https://eu1.empirikit.com and in the process of making WebComponent enablers for schools, etc. (first couple of components here: https://github.com/larsgk/poly-2-empirikit and https://github.com/larsgk/windmidi-service ).

If you require us to have a fully working solution in place under BSD on the org github site before potentially obtaining a PID, please let this request be open until it's done.

br
Lars

**Comment by Arachnid** [comment]
You do need to have firmware and hardware designs ready to go and available before we can issue you a PID. They don't have to be finished, but they do have to be at the point where you need a PID to continue, rather than theoretical, and the PID entry needs to link to the repositories for the specific hardware it's for.

I'm happy to leave the PR open until then - just ping us when you're ready.

**Comment by larsgk** [comment]
so - the specific hardware is: cheap off the shelf mbed enabled devices (for now) - specific feature detection  is handled on first handshake (e.g. some devices have a gyro, some RGB light, etc.).  We do the firmware but need a proper VID/PID (currently using a dev combo).

According to the requirements (maybe I misunderstood) - firmware running on OEM/off the shelf hardware would also be covered: "Containing schematics or **source code for a device with a USB interface**". Maybe requirements have changed? (and requires actual own produced hardware from the ground up)?

**Comment by Arachnid** [comment]
If you're using off-the-shelf hardware, you still qualify for a PID, but the requirement remains that your PID entry has to link to the specific firmware that it will be used with, and the firmware needs to be at a stage of development that necessitates one.

**Comment by larsgk** [comment]
> If you're using off-the-shelf hardware, you still qualify for a PID, but the requirement remains that your PID entry has to link to the specific firmware that it will be used with, and the firmware needs to be at a stage of development that necessitates one.

ok - sounds resonable.  I'll make it ready under the empirikit github org and ping this thread when ready.  Hopefully within days.  Would that be ok? (I was thinking we would need the PID before putting the firmware up).

**Comment by Arachnid** [comment]
Yup, that's fine. You're welcome to use the test PID in the interim, of course.

**Comment by larsgk** [comment]
Please check if we are missing something in https://github.com/empirikit

controller firmware and web enabler example (polymer 2) is there.

br
Lars

**Comment by larsgk** [comment]
@Arachnid ping :)

**Comment by Arachnid** [comment]
Thanks. Can you update your pid file to link to the specific firmware for this project? In time you may have many repositories, and it'd be hard for anyone looking at the pid record to know which ones are relevant.

**Comment by larsgk** [comment]
Sure thing - when I get to a laptop

**Comment by larsgk** [comment]
done

**Pull request merged**
