### PR TITLE
Request PID 2344 for MoaRGB project

### PR DESCRIPTION
**Pull request by jaseg**
MoaRGB is a high-power RGB LED controller with a self-documenting CDC-compatible interface.

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Where is the source for your hardware files? Thanks!

**Comment by jaseg** [comment]
Hi there,

there is no hardware files, I just soldered a bluepill (STM32F103C8T6 devboard) to an RGB LED to prototype my driver code. I intend this to be a generic "USB RGB LED" protocol that is not tied to any particular hardware.

**Review by tannewt — APPROVED** [review]
Ok! Thanks for the clarification.

**Comment by tannewt** [comment]
I added the description from the PR to trigger the CI. Everything looks good.

**Pull request merged**
