### PR TITLE
Added PID 5390 for FURiOUS - Input Display

### PR DESCRIPTION
**Pull request by furious**
Hi, I'm requesting that PID for this project I've been working on =)

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for your pull request! Please carefully read the guide at http://pid.codes/howto/ - specifically:

 - PIDs starting with 0x1xxx are reserved.
 - Your code and hardware designs must be released under an appropriate open-source license.

**Comment by furious** [comment]
Thanks, didn't noticed that 0x1xxx PIDs was reserved. I changed it to 0x0539 and added a proper license in the project repository.

**Comment by Arachnid** [comment]
Please don't use PIDs starting with 0x0xxx  either - these are reserved for pid.codes itself.

**Comment by furious** [comment]
Well, that wasn't specified in the how to, I hope that 0x539x are available...

**Comment by Arachnid** [comment]
Are you requesting the PID for "FURiOUS - Input Display", for for "Snespad"?

Snespad has Arduino source code, but doesn't appear to have any hardware designs. Is this something you intend to distribute to others? If not, you're welcome to use our test PID, 0x1209/0x0001.

**Comment by furious** [comment]
Sorry, I don't understand what do you need more. I just wanna use an exclusive PID for that project, and to do this I change the boards.txt file inside the arduino IDE before uploading the code.

**Comment by Arachnid** [comment]
Dedicated PIDs are useful to make code and driver distribution easier for hardware products. As it stands, your project is not in a state that would allow anyone else to reproduce it and use it themselves. As a result, there's not much value in allocating a PID.

Please feel free to open a new PR at such point as you have an open-source project that others can easily purchase or reproduce. In the mean time, feel free to use our test PID 0x1209/0x0001 for your own purposes.

**Pull request closed without merging**
