### PR TITLE
Refflion - Arduino compatible IoT development Board

### PR DESCRIPTION
**Pull request by Anwaarullah**
Requesting two VID/PID pairs for Refflion IoT prototyping board which is Arduino compatible and based on the Arduino Leonardo platform.

One VID/PID pair will be used the Arduino bootloader and the other will be used for uploading sketchs.

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for your pull request!

Your source repository doesn't have any source code or PCB designs checked in. In order to issue you a PID, we need solid evidence that you intend to provide your project as open source hardware, which means you need to be providing everything a user needs to recreate the project themselves.

**Comment by Anwaarullah** [comment]
Hi, thanks for your evaluation.

We had the PCB file give to us a PDF from the Design house which we uploaded earlier. We however now have access to the PCB design file and it's been uploaded to the source repository at https://bitbucket.org/PotentialLabs/refflion/src

There is currently no source code as the Bootloader's source code (which is based on Arduino's Leonardo Bootloader and is itself available as open source) first requires VID/PID pairs to be compiled, after which we'll upload the code Source files as well. 

We're testing other sample shields along with the board, post which we'll also upload the example sketch files and underlying codes.

Please let me know if you'd need more info/clarification.

Thanks.

**Comment by Arachnid** [comment]
Thanks for the update. However, you still only have images and PDFs of the schematic and board. In order to be meaningfully open source, you need to provide the CAD design files (such as Eagle, Kicad, Diptrace, or Altium), or at an absolute minimum, the gerber files that would be required by a board house to reproduce the board.

**Comment by Arachnid** [comment]
Please also make sure you upload a LICENSE to your repository, and ensure you have the rights to license all its contents under the license you choose.

**Comment by Anwaarullah** [comment]
Thanks for your feedback.

I've now uploaded the License file with proper naming convention: LICENSE.md

The PCB file which is: Refflion_PCB_File.pcb is the complete PCB design file which can be edited in CADSTAR PCB Design Software and the Gerbers exported from it.

Please let me know if this helps. Thanks.

**Comment by Arachnid** [comment]
Sorry, I missed seeing the PCB file. If you're able to provide gerbers, that will be helpful for people who don't have cadstar, but it's not mandatory.

You should update your description to remove 'upcoming', unless you intend to keep the description on pid.codes up to date with your current progress. Otherwise, this looks good to go.

**Comment by Anwaarullah** [comment]
Sure, I'll get my design house to give me the Gerber files as well.

Thanks for your feedback. I've also modified the description accordingly. I'll keep updating as we progress and also upload the accompanying source codes and design files.

Thanks :)

**Comment by Arachnid** [comment]
I meant to ask you to modify the description in the pull request, not on your own site. Obviously how you describe it on your own site is entirely up to you!

**Comment by Anwaarullah** [comment]
Sure, modified as indicated. Thanks for your help.

**Pull request merged**
