### PR TITLE
Pull request for Tempo logger board

### PR DESCRIPTION
**Pull request by rrainey**
New pid code proposed for a new design of mine.  Covered under GPL V3

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
GPL arduino code and Kicad files. Please select a new PID an older PR requested 0x2025 already.

**Comment by rrainey** [comment]
OK.  Will do.

**Review by tannewt — APPROVED** [review]

**Review by tannewt — CHANGES_REQUESTED** [review]
Still waiting on a new PID selection.

**Comment by rrainey** [comment]
OK - shifted from 2025 to 2026 and committed that change.

**Review by tannewt — APPROVED** [review]

**Pull request merged**
