### PR TITLE
Add CH569 USB3 microcontroller board PID files

### PR DESCRIPTION
**Pull request by hansfbaier**
I just stress tested and verified the latest board revision. Works!
Ready for PID.
Signed-off-by: Hans Baier <hansfbaier@gmail.com>

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Where is the bootloader source code? Hardware source looks good.

**Comment by hansfbaier** [comment]
> Where is the bootloader source code? Hardware source looks good.

There is no bootloader source code yet. This is intended for the user of the board to use for his own bootloader,
because this is a generic development board.

**Comment by tannewt** [comment]
Why do you need a PID if there isn't any code that will use it?

**Comment by hansfbaier** [comment]
> Why do you need a PID if there isn't any code that will use it?

OK, I removed the bootloader from the PR.
Will make a separate one, when we would have one.

**Review by tannewt — APPROVED** [review]
Ok, sounds good.

**Pull request merged**
