### PR TITLE
Create a A0BE as a PID for USB board

### PR DESCRIPTION
**Pull request by DelphiR**
Visit our site www.robot-develop.org and turn on the english version.

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for your pull request. Can you please make sure your repository contains source code and hardware designs, under an appropriate license - a ZIP file isn't really up to scratch!

**Comment by DelphiR** [comment]
I zipped all filles only because some of them are very large to be uploaded to github. The menu of github rejected the attempt to upload it. Notice that my repo contains the license file. Also I uploaded a PDF of schematics.

**Comment by Arachnid** [comment]
The Git command line tools or the Github app don't have any limitations on filesize; a git repository containing a zip file isn't really of much use to most people, so it'd be good if you uploaded it as a proper repository.

If you make the hardware, you need to include source files for the hardware as well, not just PDF schematics.

**Comment by DelphiR** [comment]
OK. Today I will upload using cmd git

**Comment by Arachnid** [comment]
Please open a new PR when you're happy it meets all the requirements.

**Pull request closed without merging**
