### PR TITLE
Check frontmatter owners

### PR DESCRIPTION
**Pull request by jepler**
I noticed that not much validation of the metadata is performed. I identified that it would be useful to ensure that the owner's markdown file exists as expected. Other checks, such as for all required keys having values, could be added in the future.

### CODE REVIEW

**Comment by jepler** [comment]
@tannewt ping!

**Comment by peternewman** [comment]
> I noticed that not much validation of the metadata is performed. I identified that it would be useful to ensure that the owner's markdown file exists as expected.

I think that (at least used to) be caught by the link checking stuff, althought it seems that was broken, now fixed in #791 but the jekyll build warnings don't get flagged up with test failures which is a bit unfortunate.

**Comment by jepler** [comment]
If this is redundant then please feel free to close it.

**Review by tannewt — APPROVED** [review]
Looks good to me! Thank you!

**Pull request merged**
