### PR TITLE
PID Request for Tiny Tapeout (0x5454)

### PR DESCRIPTION
**Pull request by urish**

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Where are the board design files?

**Comment by urish** [comment]
There are preliminary versions of the PCB are here: https://github.com/TinyTapeout/caravel-breakout-pcb

However, since we are going to tape out a USB (CDC ACM) Core on a physical chip, the timeline is pretty strict:

1. Taping out (submitting the final design files to the fab) in September.
2. Chips will be back in February 2024 or so. At that point, we'll be able to test them and finalize the PCB.

Since the VID / PID are hard coded during the chip manufacturing, we need to know them in advance.

**Review by tannewt — APPROVED** [review]
Open preliminary versions are fine. Good luck with the tape out!

**Comment by urish** [comment]
Thanks!

**Pull request merged**
