### PR TITLE
Add Treasure Coast Designs

### PR DESCRIPTION
**Pull request by DJDevon3**
TR-Cowbell step sequencer. Certified OSHW board.

### CODE REVIEW

**Comment by jepler** [comment]
Thanks! But there is a ci error, can you check it out?

**Comment by DJDevon3** [comment]
@jepler pushed a fix, hopefully. still new to github, did i push the new PR commit correctly?

**Comment by jepler** [comment]
I've tried to fix it (I think the owner: string had to exactly match, the witespace was throwing it off).

**Review by jepler — APPROVED** [review]
Thanks!

**Pull request merged**
