### PR TITLE
Add 1209/B737 - LrLite

### PR DESCRIPTION
**Pull request by remov-b4-flight**

### CODE REVIEW

**Comment by Arachnid** [comment]
Can you please upload hardware source files to your repository, not just the gerbers?

**Comment by remov-b4-flight** [comment]
Circuits diagram was added in the repository.

**Review by tannewt — CHANGES_REQUESTED** [review]
@remov-b4-flight Please provide user modifiable files in the native format you created them. Gerbers are too low level.

**Comment by remov-b4-flight** [comment]
Original Eagle CAD file was lost.

**Pull request closed without merging**
