### PR TITLE
renaming lowercase to uppercase for proper sorting :)

### PR DESCRIPTION
**Pull request by hvisage**
refer to #389
extracted on linux, and used `rename 'y/a-z/A-Z/' ????` git commit and push:)

### CODE REVIEW

**Comment by Arachnid** [comment]
Apologies, a merge in the meantime messed this up, can you rebase?

**Comment by hvisage** [comment]
> Apologies, a merge in the meantime messed this up, can you rebase?

Now I have to find out how to rebase...

**Comment by Arachnid** [comment]
If you generated the PR automatically,  it's probably easiest to just regenerate it.

If not, you can merge instead - merge master into your PR then fix any conflicts.

**Comment by hvisage** [comment]
I deleted & recreated the fork, so close this, opening another

**Pull request closed without merging**
