### PR TITLE
Request a USB VID/PID for Beststream-jp, Tool_CDC

### PR DESCRIPTION
**Pull request by Beststream-jp**

### CODE REVIEW

**Comment by Arachnid** [comment]
Hi,

In order to issue you a PID, you need to open-source license the source files for the design - not just the gerbers and PDF - as well as any firmware associated with the device.

Please let me know when you've updated the repository with these.

-Nick

**Comment by Beststream-jp** [comment]
Hi,
The source fileswere added to the repository.
Please check it.

Best regards,
Satoshi

**Comment by Arachnid** [comment]
Hi,

I see source code, which is great, but no indication of source files for the PCB. Are you able to include those under the OSS license and post them as well?

**Comment by Beststream-jp** [comment]
Hi, Nick.

These files will be the filing for which PSoC Creator is necessary in Integrated Design Environment (IDE).
Information about pin assignment of a chip is included in I2C2UART.cydwr.
But I2C2UART.cydwr is a binary file, so without IDE, don't the contents understand?

I added a report file of this project.
That's I2C2UART.rpt.

Information about pin assignment is mentioned from 2180 lines of this file.
I think a relation with a PCB is understood from these contents, but how about?

Best regards,
Satoshi

**Comment by Arachnid** [comment]
Hi,

I'm not asking about the source code, I'm asking about the PCB design files. You have gerbers in your repository, but not the CAD source files they were generated from by your PCB design tool. This means nobody can create derivatives of the PCB.

**Comment by Beststream-jp** [comment]
Hi,

OK.  The cad files added to the repository.
Please check it.

Satoshi

**Pull request merged**
