### PR TITLE
Request to add Etherkit Empyrean Alpha/Beta

### PR DESCRIPTION
**Pull request by NT7S**
Requesting to add Etherkit as an organization and the devices Empyrean Alpha (0x1209/0x73ea and 0x1209/0x88ea) and Empyrean Beta (0x1209/0x73eb and 0x1209/0x88eb)

### CODE REVIEW

**Comment by Arachnid** [comment]
Why do you need two PIDs for each device?

**Comment by NT7S** [comment]
The bootloader firmware (this is an Arduino IDE compatible microcontroller) enumerates in two different ways. In normal usage it enumerates as a USBCDC (virtual serial) device. However, when reset is double-tapped or the Arduino IDE initiates a sketch upload, it enumerates in sketch upload mode as an HID device. This is a derivative of the Arduino Zero, which works in the same way. Thanks

**Comment by Arachnid** [comment]
Please specify in your PID files which ones are for bootloader mode, then.

**Comment by NT7S** [comment]
Should that be specified in the title or somewhere else?

**Pull request merged**
