### PR TITLE
Request PIDs for my keyboard projects

### PR DESCRIPTION
**Pull request by kairyu**
Thank you very much for this service!

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for your PR!

Can you please add LICENSE files to your repositories so people know what license they're under?

If this is for hardware you designed yourself, you need to include design files sufficient to producing the hardware in your repositories as well.

**Comment by kairyu** [comment]
Thanks for the prompt response.
Sorry that I misunderstood the ```site``` and ```source```. I have put the URL of the source code of the hardware in the ```site``` section, and the URL of the source code of the firmware in the ```source``` section.
How shall I do since I have separated repos for hardware and firmware?

**Comment by Arachnid** [comment]
My mistake, I only checked out the source URLs. LGTM.

**Comment by kairyu** [comment]
No problem. Thank you very much for the merging.

Anyway please let me know if there is anything I should do to improve it.

**Pull request merged**
