### PR TITLE
PID request - Kameleon Core 0x7600

### PR DESCRIPTION
**Pull request by communix**

### CODE REVIEW

**Comment by Arachnid** [comment]
Is there specific hardware you're requesting a PID for? Where can we find it?

**Comment by communix** [comment]
Hi, Nick.

All the SW source code and HW schematics are in the Kameleon-Project of
Github.

The name of the HW is Kameleon Core board and here's the link of schematic.
https://github.com/kameleon-project/kameleon-board

Thanks.
Jay Kim.

**Comment by communix** [comment]
Hi, Nick.

Do you want to know any other information about our product?
Please let me know if I miss some information for your approval.

Thanks.
Jay Kim.

**Comment by Arachnid** [comment]
Can you please link to the source and design files in your submission?

**Comment by communix** [comment]
Hi Nick.

I did. please review it and let me know there's anything I need to do.

**Pull request merged**
