### PR TITLE
Request 1209/3320 for MJS2020 sensor board

### PR DESCRIPTION
**Pull request by matthijskooijman**
This board is still in development, but the latest prototype version is already published with full sources, the final board will be published in the same place. The same USB id will be used for the prototype and final versions.

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Please pick a PID that doesn't start with 0. They are reserved: http://pid.codes/1209/

**Comment by matthijskooijman** [comment]
W00ps. I checked carefully and then decided to change the PID just before submitting the PR, should have rechecked carefully.

I've rebased on top of master and changed the PID to a non-reserved value.

**Comment by matthijskooijman** [comment]
I was also planning to submit a PID checker script with github integration, but just noticed that it was already added in the recent merging spree, great! I have a small clarification for the docs, though, which I'll submit in a separate PR.

**Review by tannewt — APPROVED** [review]
Looks good! Thanks!

**Comment by matthijskooijman** [comment]
Thanks!

**Pull request merged**
