### PR TITLE
Ask for review pull request for stm32dds

### PR DESCRIPTION
**Pull request by stm32dds**
Please review my ask for PID_DD83 on VID_1209

### CODE REVIEW

**Comment by chrysn** [comment]
The software seems to be a mix of MIT-licensed and proprietary licensed data (eg. Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c); could you clarify that?

**Comment by stm32dds** [comment]
Hello   chrysn,
The short answer to your question is YES (Please read this mail till
end, point 2 is absolutely different way which I think  is applicable
in my case)
1. The ST property license (www.st.com/SLA0044) in general said that
when some portions of software are generated by it's
tool(STM32CubeIDE) they
should include "reference" for that, which is done by caption table
like this included in every  beginning of source files:
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; Copyright (c) 2015 STMicroelectronics.
  * All rights reserved.</center></h2>
  *
  * This software component is licensed by ST under Ultimate Liberty license
  * SLA0044, the "License"; You may not use this file except in compliance with
  * the License. You may obtain a copy of the License at:
  *                      www.st.com/SLA0044
  *
  ******************************************************************************
and that produced code will be run only over ST products ( not Chinese clones).
In any case this is that I understand from my long readings over
Internet with my poor English.
2. The project "stm32dds" is planed to be completely DIY type. It
consist two parts:
 - one (PCB with STM Device on it) which I discuss above
- two - Windows program by which we can START/STOP and configure device
This program I plan to put on public repository also - main reason
that I don't do this till now is that it is in too early stage i.e.
        -it open dialog window, connects to COM Port, sends desired
wave to device
        -right on this moment I am working over reading answers from device.
To do this I use "Microsoft Visual Studio Community Edition", as
driver I use "usbser.sys" and
of coarse public available examples from internet what and how to do
into coding.
If you consider that this is better "applicant" for free PID code I
will change GITHIB repository where I keep it from private to public.

As last words -> as I wrote above this is completely DIY project. I am
Electrical Design Engineer and do this project as hobby in my free
time as relax.
I don't know when I will finish this project completely. I already
achieve main challenge in this project-> to implement  DDS signal
generation
using MCU DMA channel and external R2-R matrix
Just as info - this method is about 2.5 faster than build in device
DAC (if Device has internal DAC)
So for me obtaining own PID is important just only to give this
project future live in hands of other hobbyists like me.
Because of this I create web site for this project "www.stm32dds.tk" -
when project is completely ready I will change content of this site to
hold real project  compiled sources,
schematics and PCB boards manufacturing data.

Kind regards
Ivan Ivanov


На пн, 15.02.2021 г. в 12:25 ч. chrysn <notifications@github.com> написа:

**Comment by mlyle** [comment]
> The software seems to be a mix of MIT-licensed and proprietary licensed data (eg. Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c); could you clarify that?

The vast majority of STM32 stuff that uses USB is contaminated by these files.  

First, the stuff subject Ultimate Liberty *is* open source, even if it is not compatible with many other open source licenses.

Second, literally dozens of projects have been approved by pidcodes by things that use ST's USB device library.  Is this a problem now?

**Review by tannewt — APPROVED** [review]
This is fine. Please update the links if you create your own hardware to go with it.

**Comment by stm32dds** [comment]
Thank you very much Scott. It is in my interest to update links to
hardware when it is finally ready, so I will.
Kind regards
Ivan Ivanov

На вт, 16.02.2021 г. в 4:45 ч. Scott Shawcroft <notifications@github.com>
написа:

**Pull request merged**
