### PR TITLE
Add Deneyap Development Boards

### PR DESCRIPTION
**Pull request by DogushC**
Add Deneyap Development Boards for CircuitPython.

Deneyap Kart (ESP32-WROVER-E-N4R8)
Deneyap Kart 1A (ESP32-WROVER-E-N4R8)
Deneyap Kart G (ESP32-C3FN4)

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Please link to the hardware source files and have a link to your CircuitPython fork from their README.

**Comment by DogushC** [comment]
> Please link to the hardware source files and have a link to your CircuitPython fork from their README.

Schematics: https://github.com/deneyapkart/deneyapkart-arduino-core/tree/master/docs
CircuitPython Branch: https://github.com/deneyapkart/circuitpython
Arduino IDE Repo: https://github.com/deneyapkart/deneyapkart-arduino-core

**Comment by tannewt** [comment]
We don't consider PDF schematics to be open source. We follow [the OSHWA definition](https://www.oshwa.org/definition/) that requires modifiable source files. Please post the source files and link to them.

**Comment by DogushC** [comment]
> We don't consider PDF schematics to be open source. We follow [the OSHWA definition](https://www.oshwa.org/definition/) that requires modifiable source files. Please post the source files and link to them.

I see. Is it sufficient to share a modifiable schematic as .sch format like [Robotics Masters] (https://pid.codes/1209/4D43/) ?

**Comment by DogushC** [comment]
Deneyap boards do not meet the criteria about OSHW.

**Pull request closed without merging**
