### PR TITLE
Improve options for RV003USB

### PR DESCRIPTION
**Pull request by cnlohr**
It would be really helpful if there were 3 basic devices - a bootloader, a HID descriptor and a generic non-HID descriptor for users.

See more about rv003usb here (also referenced in the changed files): https://github.com/cnlohr/rv003usb

* Update the Bootloader description.
* Add generic HID for rv003usb project.
* Add generic USB device for rv003usb project.

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Why rely on serial to differentiate projects?

It seems to me that you really want to use the test PIDs for example code. Actual products should use their own PIDs.

**Comment by cnlohr** [comment]
I would not want a separate PID for each example within my project.  There may be 10 or 15 before I'm done with this!

In general, I think it's fine, because it doesn't matter if there are multiple of the same VID/PID's that are identical when it comes to HID dongles plugged into the same system.

And it doesn't matter if there are multiple of the same for devices that are being used by bespoke code through HIDAPI.

Would it really be preferential for me to make another 5 PIDs right now?

**Comment by tannewt** [comment]
Why not use test PIDs for example code?

**Comment by cnlohr** [comment]
@tannewt  I don't understand the question.  Please elaborate, test codes meaning what?

**Comment by tannewt** [comment]
> @tannewt I don't understand the question. Please elaborate, test codes meaning what?

https://pid.codes/1209/0001/ 0001 - 0010 are private use test codes.

**Review by tannewt — COMMENTED** [review]
Looks like I've allowed the CH55 folks to have generic IDs for different descriptor combos. So, I think these are ok. However, I wouldn't suggest differentiating devices over serial. Different fixed devices should use different PIDs, not a custom user land implementation. So, please remove that portion of the comments.

**Comment by cnlohr** [comment]
Bleh sorry I missed this for so long.

**Pull request closed without merging**
