### PR TITLE
Check Open Graph via html-proofer

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
Progress on #184 .

**Comment by peternewman** [comment]
There may be one edge case with this, the checks may fail for a PR against a new PID, as the "external" URL in the Open Graph won't be valid, as the PR hasn't been approved yet. I might need to flag it as an internal link or something.

**Comment by Arachnid** [comment]
Sorry, just saw this; reviewing now.

**Comment by peternewman** [comment]
My edge case prediction was correct, but as we currently don't care about external links, it doesn't (yet) break things, making it internal should fix it:
https://travis-ci.org/pidcodes/pidcodes.github.com/jobs/167023698#L1640

**Pull request merged**
