### PR TITLE
Adding me and my Board

### PR DESCRIPTION
**Pull request by Targett363**
Trying to get the new Beta version of Circuit Python to run on modules on my board, I needed PIDs hope I've done this right I'm on my first day actually using GIT!

### CODE REVIEW

**Comment by Targett363** [comment]
Will pull again with correct licence listed!

**Review by tannewt — CHANGES_REQUESTED** [review]
Please post the native hardware design files along with a LICENSE file for them in the repos. We don't consider schematic images open because they cannot be modified to produce different hardware.

**Comment by Targett363** [comment]
I think I got it now. The jpeg was just a placeholder, I hadn't pushed the KiCad files! Thanks for all your help.

**Comment by Targett363** [comment]
I think I've managed to do it right this time.
Thanks for your time!

**Review by tannewt — CHANGES_REQUESTED** [review]
Please switch to PIDs that don't start with 0 or 1. Repo looks good! I'd suggest renaming the license file to LICENSE because it's a standard filename.

**Review by tannewt — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
