### PR TITLE
add org 0xCB; pid Helios (0xCB74)

### PR DESCRIPTION
**Pull request by Conor-Burns**

### CODE REVIEW

**Comment by tannewt** [comment]
Please make a minor change to trigger the CI again. Looks like it had broken and I merged a PR to fix it.

Software source is here: https://github.com/qmk/qmk_firmware/tree/master/keyboards/0xcb
Hardware source looks good.

**Comment by Conor-Burns** [comment]
@tannewt the CI is still failing 
```  Liquid Exception: Liquid error (/home/runner/work/pidcodes.github.com/pidcodes.github.com/_includes/orgtable.html line 6): comparison of Array with Array failed included in orgs.md
jekyll 3.9.2 | Error:  Liquid error (/home/runner/work/pidcodes.github.com/pidcodes.github.com/_includes/orgtable.html line 6): comparison of Array with Array failed included 
Error: Process completed with exit code 1.
```

**Comment by Conor-Burns** [comment]
nevermind - got it :+1:

**Review by tannewt — APPROVED** [review]

**Comment by Conor-Burns** [comment]
Thank you!

**Pull request merged**
