### PR TITLE
uCANDevices

### PR DESCRIPTION
**Pull request by Lukasz-Juranek**
Please and 3 new PIDs (0777,0776,0775) for awesome open-source products from https://ucandevices.github.io/

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Please pick PIDs that don't start with 0. They are reserved: http://pid.codes/1209/

**Comment by Lukasz-Juranek** [comment]
Thanks for feedback, i've move pids to 2777,2778, 2779

**Review by tannewt — APPROVED** [review]
Awesome! Thank you!

**Comment by tannewt** [comment]
@Lukasz-Juranek You'll want to double check that the merge was correct for you.

**Pull request merged**
