### PR TITLE
Request for PID

### PR DESCRIPTION
**Pull request by mibe**
Request for PID for my "cookie-mouse" project.

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for your pull request!

Please read carefully the guide at http://pid.codes/howto. Specifically, PIDs in the range 0x0000 - 0x1FFF are reserved; please pick a PID outside that range.

Let me know when you've updated your PR accordingly and I'll be happy to accept it.

**Comment by mibe** [comment]
Bummer, I totally skipped that. Sorry about that. I'll update the PR.

**Comment by mibe** [comment]
Alright I've updated the PR to use 0xC0C1 now.

**Comment by mibe** [comment]
Thanks!

**Pull request merged**
