### PR TITLE
Adding request for ProteanSynth PID

### PR DESCRIPTION
**Pull request by mattomatto**

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for your pull request!

This looks mostly good, but I only see a PNG in the schematics directory. Are you able to include the original design files?

**Comment by mattomatto** [comment]
It was created in Eagle and it might be a little complex to include all of the associated component libraries.  Would an image of the PCB layout suffice?

**Comment by Arachnid** [comment]
Eagle files incorporate all the necessary footprints - it'll load for another user even without the libraries you used.

The point of releasing projects as Open Source is that people can modify, remix, and make it themselves; providing just a PNG doesn't make any of that possible.

**Comment by mattomatto** [comment]
Ah ok no problem - I have updated with Eagle board and schematic files.
Thanks

**Pull request merged**
