### PR TITLE
OpenEnergyMonitor request  PID 2025 for emon

### PR DESCRIPTION
**Pull request by glynhudson**

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
CC licensed Kicad files. What firmware runs on it?

**Comment by glynhudson** [comment]
Here's the FW repo: https://github.com/awjlogan/emon32-fw

Is there anything wrong with the Kicad files?

**Comment by glynhudson** [comment]
Can this be merged? Thanks

**Comment by tannewt** [comment]
> Hi, here's the FW repo: https://github.com/awjlogan/emon32-fw

Thanks! Please link to it from the hardware repo. That way folks who follow the link from this repo can find it too. C source and license looks good.

> Is there anything wrong with the Kicad files?

Nope. Just a note to myself.

**Comment by awjlogan** [comment]
Hi @tannewt - thanks for your time on this. I've added a link in the hardware repo to the firmware in [commit 888aa99](https://github.com/awjlogan/emon32/commit/888aa99ce6e0b4ea69f16bb672d521ad6227b249). Let me know if there's anything else that would be useful.

**Review by tannewt — APPROVED** [review]
Thanks for the update!

**Review by tannewt — CHANGES_REQUESTED** [review]
Please switch to a different PID. I merged someone else with the same PID while this was under review. Sorry! I mean to go by first to PR but didn't realize the conflict.

**Comment by glynhudson** [comment]
@tannewt no worries! I've updated this PR to request PID 2025 instead

**Comment by awjlogan** [comment]
Hi @tannewt - apologies for the nudge, but just wanted to check this could be merged? Hoping to get the design out to reviewers soon. Thanks in advance, hope you've had a good weekend :)

**Review by tannewt — APPROVED** [review]
Thanks for switching!

**Comment by awjlogan** [comment]
Great, thank you @tannewt :)

**Pull request merged**
