### PR TITLE
Add Indices for Friend Team Inc and JukeBox

### PR DESCRIPTION
**Pull request by NotQuiteApex**

### CODE REVIEW

**Review by jepler — APPROVED** [review]
Thanks!

While checking the URLs I noticed that the FriendTeamInc URL comes up with a security warning, because the certificate is not valid for that domain. Mentioning it in case you were unaware.

**Comment by jepler** [comment]
Oh, and there's a nit in the markdown code too:
```
  *  internally linking to /org/Friend Team Inc/, which does not exist (line 78)
     <a href="/org/Friend Team Inc/"></a>
```
The name needs to match the filename (without .org) exactly, so I think `/org/FriendTeamInc` will be right. Once you've corrected it so that the CI is 'green' :heavy_check_mark: please feel free to ping me

**Comment by NotQuiteApex** [comment]
I noticed that security warning after the fact, it *should* be corrected now, thanks! I'll get the fixes done for Markdown now.

**Comment by NotQuiteApex** [comment]
@jepler Alrighty, all fixed!

**Review by jepler — APPROVED** [review]
Thanks!

**Pull request merged**
