### PR TITLE
Aggregate PR

### LINKED ISSUE #549: Can we help out approving code allocations?
Hi!  I'm a developer working on CircuitPython for Adafruit. I noticed that you've been unable to approve new codes for the past few months.  Would it be possible for me to help you out by reviewing these PRs to make sure they fit your guidelines?  Is there some other way I can help?

### PR DESCRIPTION
**Pull request by tannewt**
This PR aggregates outstanding PRs into one so that pending PRs will not have overlapping PIDs. Hopefully it'll be merged soon.

Existing PRs will be merged into this PR if they are clearly and openly documented and do not break the site build. Others will be skipped with a note about why below.

Closed source projects are expected to purchase their own VID: https://www.usb.org/getting-vendor-id

Fixes #549 

Here is the status of outstanding PRs:
- [x] [PR 493 - Fixed index.md file(s)](https://github.com/pidcodes/pidcodes.github.com/pull/493) Not merged, author asked for PR to be closed.
- [x] [PR 494 - added AXIOM Beta and AXIOM Remote devices ](https://github.com/pidcodes/pidcodes.github.com/pull/494) Merged
- [x] [PR 504 - Requesting PID FFB0 for OpenFFBoard](https://github.com/pidcodes/pidcodes.github.com/pull/504) Merged
- [x] [PR 508 - Request for PID 5750 with VID 0x1209 for CUAV autopilot.](https://github.com/pidcodes/pidcodes.github.com/pull/508) **NOT** merged. No native source files for the hardware.
- [x] [PR 510 - Request pid for Comrade P1](https://github.com/pidcodes/pidcodes.github.com/pull/510) Merged. Open source software only. Existing hardware.
- [x] [PR 513 - Add 1209/B737 - LrLite](https://github.com/pidcodes/pidcodes.github.com/pull/513) **NOT** merged. No native source files for the hardware.
- [x] [PR 515 - Updated website details](https://github.com/pidcodes/pidcodes.github.com/pull/515) Merged. Info update.
- [x] [PR 516 - added 0x0h.com and ours first device](https://github.com/pidcodes/pidcodes.github.com/pull/516) Merged. Hardware is public domain on EasyEDA and software is MIT.
- [x] [PR 517 - Request PID for LNE projects](https://github.com/pidcodes/pidcodes.github.com/pull/517) **NOT** merged. No obvious hardware files.
- [x] [PR 518 - Added the MIDI2CV modules.](https://github.com/pidcodes/pidcodes.github.com/pull/518) Merged.
- [x] [PR 519 - Requesting PID 0xCACE](https://github.com/pidcodes/pidcodes.github.com/pull/519) Merged.
- [x] [PR 520 - PID(8250) request for usbip-win virtual hub](https://github.com/pidcodes/pidcodes.github.com/pull/520) Merged. Software-only for Windows. Source is GPL 3
- [x] [PR 521 - Request PID C550 for ch55xduino](https://github.com/pidcodes/pidcodes.github.com/pull/521) Merged. Hardware files look like Eagle
- [x] [PR 522 - Add Command Deck device (requesting VID 1209 / PID F0DA)](https://github.com/pidcodes/pidcodes.github.com/pull/522) Merged. Software only. Hardware is breadboarded.
- [x] [PR 523 - Adding PowerMon ](https://github.com/pidcodes/pidcodes.github.com/pull/523) Merged. Code is basic but hardware files are there. README says MIT.
- [x] [PR 524 - Add Fabio Pugliese Ornellas 3D Printed Keyboard 2](https://github.com/pidcodes/pidcodes.github.com/pull/524) Merged. No PCB design. 3D files available.
- [x] [PR 525 - Request for VID 1209:5114 for the Silver project](https://github.com/pidcodes/pidcodes.github.com/pull/525) Merged. Link goes to firmware and its README has link to hardware files.
- [x] [PR 526 - Added own organisation and PID](https://github.com/pidcodes/pidcodes.github.com/pull/526) Merged. Some site links are bad but the repo is available with source.
- [x] [PR 527 - uCANDevices](https://github.com/pidcodes/pidcodes.github.com/pull/527) **NOT** merged uses 0xxx PIDs.
- [x] [PR 528 - Added lophtware's USB2.0 Type-C / PIC32 Breakout Board.](https://github.com/pidcodes/pidcodes.github.com/pull/528) Merged. Clearly licensed and I think the raw files. Altium maybe?
- [x] [PR 529 - PID request for CatWAN Farmer](https://github.com/pidcodes/pidcodes.github.com/pull/529) Merged. License is only noted in README. Code is Arduino examples.
- [x] [PR 530 - Request for PID 5555](https://github.com/pidcodes/pidcodes.github.com/pull/530) Merged. License is clear. Hardware files in zip but in native Kicad format.
- [x] [PR 531 - ErgoKB Phoenix Board](https://github.com/pidcodes/pidcodes.github.com/pull/531) Merged. Existing open firmware. Hardware is open, kicad files.
- [x] [PR 532 - Request PID 8787 & 8788](https://github.com/pidcodes/pidcodes.github.com/pull/532) **NOT** merged. Files say explicitly "All rights reserved".
- [x] [PR 533 - Request PID C0D4 for Autumnal](https://github.com/pidcodes/pidcodes.github.com/pull/533) **NOT** merged. No obvious hardware files even though the code appears to be for custom hardware.
- [x] [PR 534 - Request PID 0x7522 for Makbit MIDI2USB device.](https://github.com/pidcodes/pidcodes.github.com/pull/534) Merged.
- [x] [PR 535 - Use same PID code for ODrive v4 also](https://github.com/pidcodes/pidcodes.github.com/pull/535) Merged. Updated info.
- [x] [PR 538 - PID Request for RE5](https://github.com/pidcodes/pidcodes.github.com/pull/538) Merged. Hardware MIT. Firmware is QMK.
- [x] [PR 539 - Submit PID request for Abies](https://github.com/pidcodes/pidcodes.github.com/pull/539) **NOT** merged. No clear firmware.
- [x] [PR 540 - PID Request for te96](https://github.com/pidcodes/pidcodes.github.com/pull/540) Merged. Same person as 538.
- [x] [PR 541 - Adding CM20](https://github.com/pidcodes/pidcodes.github.com/pull/541) Merged. Software is micro:bit and hardware files are in `assets`.
- [x] [PR 542 - PID request for BastWIFI](https://github.com/pidcodes/pidcodes.github.com/pull/542) Merged. Link is only to hardware but software is CircuitPython, an open source version.
- [x] [PR 543 - Add Lab11 org and TotTag device with PID 5000](https://github.com/pidcodes/pidcodes.github.com/pull/543) Merged. All MIT.
- [x] [PR 544 - Requesting PID 0D11 and 0D10 for Odiin](https://github.com/pidcodes/pidcodes.github.com/pull/544) **NOT** merged uses 0xxx PIDs. All firmware. Hardware is breadboarded with a bridge that is open.
- [x] [PR 545 - Add uwmisl org and PurpleDrop PID](https://github.com/pidcodes/pidcodes.github.com/pull/545) Merged.
- [x] [PR 546 - Updated usage of 4321](https://github.com/pidcodes/pidcodes.github.com/pull/546) Merged.
- [x] [PR 547 - PID request for N32B](https://github.com/pidcodes/pidcodes.github.com/pull/547) Merged.
- [x] [PR 548 - add rrainey organization and associated pid codes](https://github.com/pidcodes/pidcodes.github.com/pull/548) Merged.
- [x] [PR 550 - Request PID 2344 for MoaRGB project](https://github.com/pidcodes/pidcodes.github.com/pull/550) **NOT** merged. No hardware files.
- [x] [PR 551 - add LinklayerLabs org and CANtact Pro device (0x1209/0x1111)](https://github.com/pidcodes/pidcodes.github.com/pull/551) **NOT** merged. source link is broken.
- [x] [PR 552 - sinara/stabilizer: add org and pid](https://github.com/pidcodes/pidcodes.github.com/pull/552) **NOT** merged. No license in hardware repo.
- [x] [PR 553 - Request for the probe-rs project's HS probe, an open source probe](https://github.com/pidcodes/pidcodes.github.com/pull/553) Merged.
- [x] [PR 555 - Combine Reality PID request](https://github.com/pidcodes/pidcodes.github.com/pull/555) **NOT** merged. Feedback left on PR
- [x] [PR 556 - PID request for BASTBLE](https://github.com/pidcodes/pidcodes.github.com/pull/556) Merged. Link is only to hardware but software is CircuitPython, an open source version.
- [x] [PR 558 - Requests USB ID 1209:3845](https://github.com/pidcodes/pidcodes.github.com/pull/558) Merged. Link is only to hardware. Software is QMK which is open source.
- [x] [PR 559 - Add registration of a default product ID for PAPPL-based printer appl…](https://github.com/pidcodes/pidcodes.github.com/pull/559) Merged. Software only. Runs on embedded Linux.
- [x] [PR 560 - Request PID 4DDD for Oak Development Tech CP Sapling](https://github.com/pidcodes/pidcodes.github.com/pull/560) **NOT** merged. Feedback left on PR.
- [x] [PR 562 - Request PID 0x1337 for Schwurbler](https://github.com/pidcodes/pidcodes.github.com/pull/562) **NOT** merged. 0x1xxx PIDs are reserved for the original VID owner.
- [x] [PR 564 - Adding me and my Board](https://github.com/pidcodes/pidcodes.github.com/pull/564) **NOT** merged. No hardware source files. Software is CircuitPython.
- [x] [PR 565 - Request 1209/0721 for MJS2020 sensor board](https://github.com/pidcodes/pidcodes.github.com/pull/565) **NOT** merged uses 0xxx PID. Software is Arduino and hardware Kicad source is linked to.

### CODE REVIEW

**Comment by alexgubanow** [comment]
hello, can you clarify situation once again. my PR is #516 and you wrote that its merged, but i don't see it on pid.codes web page, so can I start use pid? I just have filled form on OSHWA certification.

**Comment by tannewt** [comment]
Hi @alexgubanow, it won't appear on the webpage until this PR or yours is merged by @Arachnid. My intent with this PR was to make it easy for @Arachnid to get caught up and to also ensure there are no conflicts between pending requests. I think it's safe to use the PID because it hasn't conflicted with anyone else. It won't be official until it is actually merged.

**Comment by tannewt** [comment]
Ok, #527, #544 and #565 were removed because they use new 0xxx PIDs.

**Review by Arachnid — APPROVED** [review]

**Comment by sabas1080** [comment]
@tannewt thanks!

**Pull request merged**
