### PR TITLE
New USB PID request for Modal (0xBEEF).

### PR DESCRIPTION
**Pull request by modalpdx**
Following the directions on http://pid.codes/howto/, I have added two files for my organization and the open hardware device that I'm designing and I have initiated this pull request. I am not sure if anything else is required of me, but I am hoping I will be notified if this is the case.

Thank you for considering this request!

E.

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for your pull request! The 'owner' field of your pid file should specify your org - in this case, 'modal' (note the lower case 'm'). Otherwise, this is all good.

**Comment by modalpdx** [comment]
Ouch, major oversight on my part! The owner has been corrected.

As this is my first pull request, I confess I'm not 100% sure about the process. Is the existing pull request still valid or do I need to close this one and make another? I suspect this pull request is okay, but it can't hurt to ask. Thanks!

**Comment by Arachnid** [comment]
The pull request automatically updates with any changes you make to the branch, so you're all good.

**Comment by modalpdx** [comment]
Awesome, thanks!

**Pull request merged**
