### PR TITLE
Create index.md

### PR DESCRIPTION
**Pull request by InventureElectronics**
Create index.md for request of FF00 PID

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for your pull request!

In order to issue you a PID, both your hardware and software need to be open-source. Do you have published hardware designs anywhere?

**Comment by InventureElectronics** [comment]
I have added the hardware schematics to the usbtoserial repository.

**Comment by InventureElectronics** [comment]
I added the hardware schematics to the usbtoserial github repository.

**Comment by Arachnid** [comment]
Hi,

You need to include the actual design files for the hardware you're proposing to use this for. They need to be enough for a third-party to adapt and make your device; this is the nature of open hardware. At a minimum, this would include schematics and gerbers for the actual device in question, preferably design source files as well.

Since I'm fairly sure you're not making an Arduino Uno, I'm closing this PR. Feel free to open another one with all the requirements if you feel you meet them.

**Pull request closed without merging**
